# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f7fad22e15491651599a3f6cfe1b656540aa5508bdaaedcbb359efbd44d6781925e81ff5a32fb9cab026ad937283112adec46892462ac9412a13341caa99805

test:
  secret_key_base: ba98c0ca53c5f8123c362ee34b4aa51bd2390ee3ab09231d46b8cf163ddd94d6faa354c1b3489640a07c7c2309bafddbe6d600a1cffac1318c7490f4bdb90f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
